#!/usr/bin/env python3
"""
One-time setup: authorize morning_digest.py to read Gmail and Calendar.

Steps:
  1. Go to https://console.cloud.google.com/ and create a project.
  2. Enable the Gmail API and Google Calendar API.
  3. Create OAuth 2.0 credentials (Desktop app type).
  4. Download the JSON file and pass its path to this script:

       python3 setup_google_auth.py /path/to/client_secret.json

  5. A browser window will open. Sign in and grant access.
  6. The script writes credentials to ~/.claude/morning_digest.env.
"""

import json
import os
import sys
import urllib.parse
import urllib.request
import webbrowser
from http.server import BaseHTTPRequestHandler, HTTPServer

ENV_FILE = os.path.expanduser("~/.claude/morning_digest.env")
SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/gmail.compose",
    "https://www.googleapis.com/auth/calendar.readonly",
]
REDIRECT_URI = "http://localhost:8765"


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(__doc__)

    with open(sys.argv[1]) as f:
        creds_json = json.load(f)

    info = creds_json.get("installed") or creds_json.get("web")
    if not info:
        sys.exit("Unrecognised credential file format.")

    client_id = info["client_id"]
    client_secret = info["client_secret"]
    auth_endpoint = info.get("auth_uri", "https://accounts.google.com/o/oauth2/auth")
    token_endpoint = info.get("token_uri", "https://oauth2.googleapis.com/token")

    # Build authorization URL
    params = {
        "client_id": client_id,
        "redirect_uri": REDIRECT_URI,
        "response_type": "code",
        "scope": " ".join(SCOPES),
        "access_type": "offline",
        "prompt": "consent",
    }
    auth_url = auth_endpoint + "?" + urllib.parse.urlencode(params)

    print(f"\nOpening browser for Google authorization…\n{auth_url}\n")
    webbrowser.open(auth_url)

    # Tiny local server to capture the redirect
    code_holder: list[str] = []

    class _Handler(BaseHTTPRequestHandler):
        def log_message(self, *_):
            pass

        def do_GET(self):
            qs = urllib.parse.parse_qs(urllib.parse.urlparse(self.path).query)
            if "code" in qs:
                code_holder.append(qs["code"][0])
                self.send_response(200)
                self.end_headers()
                self.wfile.write(b"<h2>Authorization complete. You can close this tab.</h2>")
            else:
                self.send_response(400)
                self.end_headers()
                self.wfile.write(b"<h2>Missing code parameter.</h2>")

    server = HTTPServer(("localhost", 8765), _Handler)
    print("Waiting for Google to redirect back (listening on :8765)…")
    while not code_holder:
        server.handle_request()
    server.server_close()

    code = code_holder[0]

    # Exchange code for tokens
    data = urllib.parse.urlencode({
        "code": code,
        "client_id": client_id,
        "client_secret": client_secret,
        "redirect_uri": REDIRECT_URI,
        "grant_type": "authorization_code",
    }).encode()
    req = urllib.request.Request(
        token_endpoint,
        data=data,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        method="POST",
    )
    with urllib.request.urlopen(req) as resp:
        tokens = json.loads(resp.read())

    refresh_token = tokens.get("refresh_token")
    if not refresh_token:
        sys.exit("No refresh_token in response — make sure you added 'prompt=consent'.")

    # Prompt for remaining config
    to_email = input("\nEnter the Gmail address to deliver the digest to: ").strip()
    api_key = input("Enter your Anthropic API key: ").strip()

    # Write env file
    env_content = f"""# morning_digest.py configuration
# Generated by setup_google_auth.py — do not commit this file.
GOOGLE_CLIENT_ID={client_id}
GOOGLE_CLIENT_SECRET={client_secret}
GOOGLE_REFRESH_TOKEN={refresh_token}
DIGEST_TO_EMAIL={to_email}
ANTHROPIC_API_KEY={api_key}
CLAUDE_MODEL=claude-sonnet-4-6
TIMEZONE_OFFSET=-06:00
"""
    os.makedirs(os.path.dirname(ENV_FILE), exist_ok=True)
    with open(ENV_FILE, "w") as f:
        f.write(env_content)
    os.chmod(ENV_FILE, 0o600)

    print(f"\n✓ Credentials saved to {ENV_FILE}")
    print("\nNext step — install the 5 AM cron job:")
    print("  python3 /home/user/ClaudeRoutines/install_cron.py\n")


if __name__ == "__main__":
    main()
